include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_string_interpolations: false
    unnecessary_to_list_in_spreads: false
    use_super_parameters: false
